[package]
name = "rust"
version = "1.85.0"
edition = "2021"

[dependencies]
colored = "2.0.0"
dotenv = "0.15.0"
sqlx = { version = "0.8.3", features = ["sqlite", "macros", "runtime-tokio-rustls"] }
tokio = { version = "1.43.0", features = ["full"] }
